# Flag definitions for configuration.
#
# By ABed Na'aran December 2023

TOP_DIR := /home/amber/projects/advent_of_code

DAYS :=  $(wildcard $(TOP_DIR)/day_*)
INCLUDE_FLAG := $(foreach DIR, $(DAYS), -I$(DIR))
LIBS_DIRS_FLAGS := $(foreach DIR, $(DAYS), -L$(DIR))
LIBS_FLAGS := $(foreach DIR, $(DAYS), -l$(shell basename $(DIR)))

CXX := g++
CXXFLAGS := -Wall -Werror -pedantic -Wextra -Wfatal-errors \
			-Wsign-conversion $(INCLUDE_FLAG) -I. -g
LIBS := $(LIBS_DIRS_FLAGS) $(LIBS_FLAGS) 
